spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none
logging:
  level:
    root: info
    com.shili: debug
  file:
    path: log/blog-dev