spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  profiles:
    active: dev

  mail:
    #smtp服务主机
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 11799220@qq.com
    #授权码
    password: sjgoerretdrlbhcf
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587

comment:
  avatar: https://www.hualigs.cn/image/60a11871c8904.jpg
