spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?userUnicode=true&characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456
logging:
  level:
    root: warn
    com.shili: debug
  file:
    path: log/blog-pro
  server:
      port: 8081
